
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: discord
  name: bot
  labels:
    app: bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bot
  template:
    metadata:
      labels:
        app: bot
    spec:
      restartPolicy: Always
      containers:
        - name: bot
          image: stephanzlatarev/discordbot:2024.12.15-21.20
          command: ["sh", "-c", "cp /etc/discordbot/config/config.py /bot/config.py; /usr/local/bin/python ./bot.py"]
          volumeMounts:
            - name: config
              mountPath: /etc/discordbot/config
              readOnly: true
      volumes:
        - name: config
          secret:
            secretName: config
 