name: Release

on:
  - push

jobs:

  Release:
    runs-on: ubuntu-latest
    steps:
      - name: Select release version
        id: version
        run: printf 'tag=${{ env.DOCKERHUB_USERNAME }}/discordbot:%(%Y.%m.%d-%H.%M)T' >> $GITHUB_OUTPUT

      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Publish Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ steps.version.outputs.tag }}

      - name: Update Kubernetes descriptors
        run: sed -i -e 's|aiarena/discordbot|${{ steps.version.outputs.tag }}|g' kubernetes/deployment.yaml

      - name: Push to release branch
        run: |
          git config --global user.name 'AI Arena'
          git config --global user.email 'staff@aiarena.net'
          git commit -a -m 'Release ${{ steps.version.outputs.tag }}'
          git push release
